name: "CI"

on:
  push:
    branches:
        - custom
  pull_request:
    branches:
        - custom

jobs:
  CMake:
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu 22.04 x64
            runner: ubuntu-22.04
            cmake_generator: Unix Makefiles
            cmake_defines: "-DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/openems-install"
          - name: Ubuntu 22.04 ARM
            runner: ubuntu-22.04-arm
            cmake_generator: Ninja
            cmake_defines: "-DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/openems-install"
          - name: Ubuntu 24.04 x64
            runner: ubuntu-24.04
            cmake_generator: Unix Makefiles
            cmake_defines: "-DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/openems-install"
          - name: Ubuntu 24.04 ARM
            runner: ubuntu-24.04-arm
            cmake_generator: Ninja
            cmake_defines: "-DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/openems-install"
          - name: macOS 14
            runner: macos-14
            cmake_generator: Xcode
            cmake_defines: "-DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/openems-install"
          - name: Windows MSVC
            runner: windows-latest
            no_sudo: 1
            cmake_defines: "-DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/openems-install"
            cmake_generator: Ninja

    steps:
      - name: "Checkout openEMS-Project"
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: df -h /

      - name: Set environment variables (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "BUILD_ARGS=-j8" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Set environment variables (Unix)
        if: runner.os != 'Windows'
        run: |
          PROC_COUNT=8

          if [ "${{ matrix.cmake_generator }}" == "Xcode" ]; then
              # Xcode generates a lot of output, suppress it so only warnings and errors are visible
              BUILD_ARGS="-j$PROC_COUNT"
          else
              BUILD_ARGS="-j$PROC_COUNT"
          fi

          echo BUILD_ARGS=$BUILD_ARGS >> $GITHUB_ENV

      - name: "[Windows] Set up MSVC Developer Command Prompt"
        if: runner.os == 'Windows'
        uses: seanmiddleditch/gha-setup-vsdevenv@master

      - name: "Configuring"
        run: |
          cmake --version
          mkdir build_cmake
          pushd build_cmake
          cmake -G "${{ matrix.cmake_generator }}" ${{ matrix.cmake_defines }}  ..

      - name: "Building"
        working-directory: build_cmake
        run: |
          cmake --build . $BUILD_ARGS

      - run: df -h /
        if: success() || failure()

      - name: Installing
        working-directory: build_cmake
        run: |
          cmake --build . --target install

      - run: df -h /
        if: success() || failure()

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: openems_${{ matrix.runner }}
          path: ${{ github.workspace }}/openems-install

